# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lamstar.ui'
#
# Created: Sat Dec  1 19:06:23 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.resultLabel = QtGui.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(410, 250, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setText(_fromUtf8(""))
        self.resultLabel.setObjectName(_fromUtf8("resultLabel"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 300, 491, 251))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.imageResultLabel = QtGui.QLabel(self.centralwidget)
        self.imageResultLabel.setGeometry(QtCore.QRect(330, 20, 150, 200))
        self.imageResultLabel.setFrameShape(QtGui.QFrame.Panel)
        self.imageResultLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageResultLabel.setLineWidth(1)
        self.imageResultLabel.setMidLineWidth(1)
        self.imageResultLabel.setText(_fromUtf8(""))
        self.imageResultLabel.setObjectName(_fromUtf8("imageResultLabel"))
        self.imageInputLabel = QtGui.QLabel(self.centralwidget)
        self.imageInputLabel.setGeometry(QtCore.QRect(20, 20, 150, 200))
        self.imageInputLabel.setFrameShape(QtGui.QFrame.Panel)
        self.imageInputLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageInputLabel.setLineWidth(1)
        self.imageInputLabel.setMidLineWidth(1)
        self.imageInputLabel.setText(_fromUtf8(""))
        self.imageInputLabel.setObjectName(_fromUtf8("imageInputLabel"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tmpLabel1 = QtGui.QLabel(self.centralwidget)
        self.tmpLabel1.setGeometry(QtCore.QRect(330, 250, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(11)
        self.tmpLabel1.setFont(font)
        self.tmpLabel1.setObjectName(_fromUtf8("tmpLabel1"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 280, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMain = QtGui.QMenu(self.menubar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        self.menuLamstar = QtGui.QMenu(self.menubar)
        self.menuLamstar.setObjectName(_fromUtf8("menuLamstar"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Training_Folder = QtGui.QAction(MainWindow)
        self.actionLoad_Training_Folder.setObjectName(_fromUtf8("actionLoad_Training_Folder"))
        self.actionLoad_Testing_Folder = QtGui.QAction(MainWindow)
        self.actionLoad_Testing_Folder.setObjectName(_fromUtf8("actionLoad_Testing_Folder"))
        self.actionTrain = QtGui.QAction(MainWindow)
        self.actionTrain.setObjectName(_fromUtf8("actionTrain"))
        self.actionRun_Test = QtGui.QAction(MainWindow)
        self.actionRun_Test.setObjectName(_fromUtf8("actionRun_Test"))
        self.actionProperties = QtGui.QAction(MainWindow)
        self.actionProperties.setObjectName(_fromUtf8("actionProperties"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPrepare_for_training = QtGui.QAction(MainWindow)
        self.actionPrepare_for_training.setObjectName(_fromUtf8("actionPrepare_for_training"))
        self.actionPrepare_for_testing = QtGui.QAction(MainWindow)
        self.actionPrepare_for_testing.setObjectName(_fromUtf8("actionPrepare_for_testing"))
        self.menuMain.addAction(self.actionLoad_Training_Folder)
        self.menuMain.addAction(self.actionLoad_Testing_Folder)
        self.menuLamstar.addAction(self.actionPrepare_for_training)
        self.menuLamstar.addAction(self.actionPrepare_for_testing)
        self.menuLamstar.addSeparator()
        self.menuLamstar.addAction(self.actionTrain)
        self.menuLamstar.addAction(self.actionRun_Test)
        self.menuWindow.addAction(self.actionProperties)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuLamstar.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Queried Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.tmpLabel1.setText(QtGui.QApplication.translate("MainWindow", "Result:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Log :", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMain.setTitle(QtGui.QApplication.translate("MainWindow", "Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLamstar.setTitle(QtGui.QApplication.translate("MainWindow", "Lamstar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Training_Folder.setText(QtGui.QApplication.translate("MainWindow", "Load Training Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Testing_Folder.setText(QtGui.QApplication.translate("MainWindow", "Load Testing Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrain.setText(QtGui.QApplication.translate("MainWindow", "Train", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Test.setText(QtGui.QApplication.translate("MainWindow", "Run Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProperties.setText(QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrepare_for_training.setText(QtGui.QApplication.translate("MainWindow", "Prepare for training", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrepare_for_testing.setText(QtGui.QApplication.translate("MainWindow", "Prepare for testing", None, QtGui.QApplication.UnicodeUTF8))

